# action that runs monthly and add maintainer as a custom property
# to all repositories in this organization
name: Add Maintainer as Custom Property to Repositories
on:
  schedule:
    - cron: '0 0 27 * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: brave/security-action/actions/add-maintainer-custom-property@main
        with:
          ignore_maintainers: brave-builds,brave-browser-releases,brave-support-admin
          debug: false
          github_token: ${{ secrets.CUSTOM_PROPERTY_MANAGER_GITHUB_TOKEN }}
          slack_token: ${{ secrets.HOTSPOTS_SLACK_TOKEN }}