name: Check New Repos
on:
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check new repos
        uses: brave/security-action/actions/check-new-repos@main
        with:
          github_token: ${{ secrets.ORG_READ_GITHUB_TOKEN }}
          slack_token: ${{ secrets.HOTSPOTS_SLACK_TOKEN }}
          debug: false