name: Weekly Dependabot Nudge
on:
  schedule:
    # Run at 9am UTC every Monday
    - cron: "0 9 * * 1"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: dependabot nudge
        uses: brave/security-action/actions/dependabot-nudge@main
        with:
          github_token: ${{ secrets.DEPENDABOT_NUDGE_GITHUB_TOKEN }}
          slack_token: ${{ secrets.HOTSPOTS_SLACK_TOKEN }}
          gh_to_slack_user_map: ${{ secrets.GH_TO_SLACK_USER_MAP }}
          debug: false