name: Weekly Dependabot Auto Dismiss
on:
  schedule:
    # Run at 24:00 UTC every Monday
    - cron: "0 0 * * 1"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: dependabot auto dismiss
        uses: brave/security-action/actions/dependabot-auto-dismiss@main
        with:
          github_token: ${{ secrets.DEPENDABOT_AUTO_DISMISS_GITHUB_TOKEN }}
          slack_token: ${{ secrets.HOTSPOTS_SLACK_TOKEN }}
          debug: false