name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 * * *"
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@3eb47f21355191080dca0f7662d45c192d2ef64d # v2.0.7
        with:
          workflow_files: "keepalive-workflow.yml, add-maintainer-custom-property.yml, add-runtime-custom-property.yml, check-new-repos.yml, copy-repo-secrets-to-org-secrets.yml, dependabot-auto-dismiss.yml, dependabot-nudge.yml, older-than-2y.yml, renovate-sanity-check.yml"
          time_elapsed: "0"
