name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: gautamkrishnar/keepalive-workflow@2a8ae70f39b79fb50659d17ccc6f372f461813b2 # 2.0.10
        with:
          workflow_files: "keepalive.yml, add-maintainer-custom-property.yml, add-runtime-custom-property.yml, check-new-repos.yml, copy-repo-secrets-to-org-secrets.yml, dependabot-auto-dismiss.yml, dependabot-nudge.yml, older-than-2y.yml, renovate-sanity-check.yml"
          time_elapsed: "0"
