name: Older Than 2 Years Informer
on:
  schedule:
    # Every month, first day of the month
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: older than 2 years informer
        uses: brave/security-action/actions/older-than-2y@main
        with:
          github_token: ${{ secrets.ORG_READ_GITHUB_TOKEN }}
          slack_token: ${{ secrets.HOTSPOTS_SLACK_TOKEN }}
          debug: false