# action that runs monthly and check if all repositories in the organization are following the renovate central configuration
# to all repositories in this organization
name: Renovate Sanity Check
on:
  schedule:
    - cron: '0 0 15 * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate Sanity Check
        uses: brave/security-action/actions/renovate-sanity-check@main
        with:
          github_token: ${{ secrets.CUSTOM_PROPERTY_MANAGER_GITHUB_TOKEN }}
          slack_token: ${{ secrets.HOTSPOTS_SLACK_TOKEN }}
          debug: false