name: Slack Cleanup
on:
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:
permissions: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: slack cleanup
        uses: brave/security-action/actions/cleanup@main
        with:
          github_token: ${{ secrets.SLACK_CLEANUP_GITHUB_TOKEN }}
          slack_token: ${{ secrets.HOTSPOTS_SLACK_TOKEN }}
          debug: false
